<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Income Report</title>
    <style>
        body { font-family: 'DejaVu Sans', sans-serif; color: #333; line-height: 1.5; font-size: 12px; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #f3f4f6; padding-bottom: 20px; }
        .header h1 { color: #111827; margin: 0; font-size: 24px; }
        .header p { color: #6b7280; margin: 5px 0 0; font-size: 14px; }
        .section-title { background: #f9fafb; padding: 10px; border-left: 4px solid #10b981; font-weight: bold; margin: 20px 0 10px; color: #111827; text-transform: uppercase; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { background: #f3f4f6; color: #4b5563; font-weight: bold; text-align: left; padding: 10px; border-bottom: 1px solid #e5e7eb; text-transform: uppercase; }
        td { padding: 10px; border-bottom: 1px solid #f3f4f6; }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .font-bold { font-weight: bold; }
        .text-emerald { color: #059669; }
        .footer { margin-top: 50px; text-align: center; font-size: 10px; color: #9ca3af; border-top: 1px solid #f3f4f6; padding-top: 20px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Financial Income Report</h1>
        <p>Period: {{ $startDate }} to {{ $endDate }}</p>
    </div>

    <div class="section-title">Payment Method Breakdown</div>
    <table>
        <thead>
            <tr>
                <th>Method</th>
                <th class="text-center">Transactions</th>
                <th class="text-right">Total Income</th>
            </tr>
        </thead>
        <tbody>
            @foreach($paymentMethods as $method)
                <tr>
                    <td style="text-transform: uppercase;">{{ $method->payment_method }}</td>
                    <td class="text-center">{{ $method->count }}</td>
                    <td class="text-right font-bold text-emerald">${{ number_format($method->total, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr style="background: #f9fafb;">
                <td colspan="2" class="font-bold">GRAND TOTAL</td>
                <td class="text-right font-bold text-emerald" style="font-size: 16px;">${{ number_format($paymentMethods->sum('total'), 2) }}</td>
            </tr>
        </tfoot>
    </table>

    <div class="section-title">Daily Income Log</div>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th class="text-right">Income</th>
            </tr>
        </thead>
        <tbody>
            @foreach($dailyIncome as $day)
                <tr>
                    <td>{{ date('d M, Y (l)', strtotime($day->date)) }}</td>
                    <td class="text-right font-bold">${{ number_format($day->total, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by {{ config('app.name') }} POS System on {{ date('Y-m-d H:i:s') }}
    </div>
</body>
</html>
