<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Orders Report</title>
    <style>
        body { font-family: 'DejaVu Sans', sans-serif; color: #333; line-height: 1.5; font-size: 10px; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #f3f4f6; padding-bottom: 20px; }
        .header h1 { color: #111827; margin: 0; font-size: 20px; }
        .header p { color: #6b7280; margin: 5px 0 0; font-size: 12px; }
        .section-title { background: #f9fafb; padding: 8px; border-left: 4px solid #3b82f6; font-weight: bold; margin: 20px 0 10px; color: #111827; text-transform: uppercase; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { background: #f3f4f6; color: #4b5563; font-weight: bold; text-align: left; padding: 8px; border-bottom: 1px solid #e5e7eb; text-transform: uppercase; }
        td { padding: 8px; border-bottom: 1px solid #f3f4f6; }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .font-bold { font-weight: bold; }
        .status-badge { padding: 2px 6px; border-radius: 4px; font-size: 8px; text-transform: uppercase; font-weight: bold; }
        .footer { margin-top: 50px; text-align: center; font-size: 8px; color: #9ca3af; border-top: 1px solid #f3f4f6; padding-top: 20px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Orders & Transactions Report</h1>
        <p>Period: {{ $startDate }} to {{ $endDate }}</p>
    </div>

    <div class="section-title">Order Type Summary</div>
    <table>
        <thead>
            <tr>
                <th>Order Type</th>
                <th class="text-center">Count</th>
                <th class="text-right">Revenue</th>
            </tr>
        </thead>
        <tbody>
            @foreach($ordersByType as $type)
                <tr>
                    <td style="text-transform: capitalize;">{{ str_replace('_', ' ', $type->order_type) }}</td>
                    <td class="text-center">{{ $type->count }}</td>
                    <td class="text-right font-bold">${{ number_format($type->revenue, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="section-title">Order Status Distribution</div>
    <table>
        <thead>
            <tr>
                <th>Status</th>
                <th class="text-center">Count</th>
            </tr>
        </thead>
        <tbody>
            @foreach($ordersByStatus as $status)
                <tr>
                    <td style="text-transform: capitalize;">{{ $status->status }}</td>
                    <td class="text-center">{{ $status->count }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by {{ config('app.name') }} POS System on {{ date('Y-m-d H:i:s') }}
    </div>
</body>
</html>
