<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Sales Report</title>
    <style>
        body { font-family: 'DejaVu Sans', sans-serif; color: #333; line-height: 1.5; font-size: 12px; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #f3f4f6; padding-bottom: 20px; }
        .header h1 { color: #111827; margin: 0; font-size: 24px; }
        .header p { color: #6b7280; margin: 5px 0 0; font-size: 14px; }
        .section-title { background: #f9fafb; padding: 10px; border-left: 4px solid #f59e0b; font-weight: bold; margin: 20px 0 10px; color: #111827; text-transform: uppercase; font-size: 14px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { background: #f3f4f6; color: #4b5563; font-weight: bold; text-align: left; padding: 10px; border-bottom: 1px solid #e5e7eb; text-transform: uppercase; font-size: 10px; }
        td { padding: 10px; border-bottom: 1px solid #f3f4f6; }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .font-bold { font-weight: bold; }
        .text-emerald { color: #059669; }
        .footer { margin-top: 50px; text-align: center; font-size: 10px; color: #9ca3af; border-top: 1px solid #f3f4f6; padding-top: 20px; }
        .summary-box { margin-bottom: 30px; }
        .summary-item { display: inline-block; width: 30%; text-align: center; }
        .summary-item label { display: block; color: #6b7280; font-size: 10px; text-transform: uppercase; }
        .summary-item value { display: block; font-size: 18px; font-weight: bold; color: #111827; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Sales Analysis Report</h1>
        <p>Period: {{ $startDate }} to {{ $endDate }}</p>
    </div>

    <div class="summary-box">
        <div class="summary-item">
            <label>Total Items Sold</label>
            <value>{{ number_format($topItems->sum('total_qty')) }}</value>
        </div>
        <div class="summary-item">
            <label>Gross Sales</label>
            <value>${{ number_format($topItems->sum('total_sales'), 2) }}</value>
        </div>
        <div class="summary-item">
            <label>Report Date</label>
            <value>{{ date('d M, Y') }}</value>
        </div>
    </div>

    <div class="section-title">Top Selling Items</div>
    <table>
        <thead>
            <tr>
                <th>Item Name</th>
                <th class="text-center">Quantity Sold</th>
                <th class="text-right">Total Revenue</th>
            </tr>
        </thead>
        <tbody>
            @foreach($topItems as $item)
                <tr>
                    <td>{{ $item->name }}</td>
                    <td class="text-center">{{ number_format($item->total_qty) }}</td>
                    <td class="text-right font-bold text-emerald">${{ number_format($item->total_sales, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="section-title">Sales by Category</div>
    <table>
        <thead>
            <tr>
                <th>Category</th>
                <th class="text-right">Total Revenue</th>
                <th class="text-right">Share</th>
            </tr>
        </thead>
        <tbody>
            @php $totalSales = $categorySales->sum('total_sales') ?: 1; @endphp
            @foreach($categorySales as $cat)
                <tr>
                    <td>{{ $cat->name }}</td>
                    <td class="text-right font-bold">${{ number_format($cat->total_sales, 2) }}</td>
                    <td class="text-right">{{ number_format(($cat->total_sales / $totalSales) * 100, 1) }}%</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by {{ config('app.name') }} POS System on {{ date('Y-m-d H:i:s') }}
    </div>
</body>
</html>
